version: "3"

services:
  cockroachdb:
    image: "cockroachdb/cockroach:latest-v24.1"
    ports:
      - "26257:26257"
      - "5432:5432"
    restart: always
    volumes:
      - ./db-data/cockroach:/cockroach/cockroach-data
    command: start-single-node --insecure

  #  start mailhog
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
